language: python

matrix:
    include:
        - python: "3.6"
          env: TOXENV=lint-py36
        - python: "3.5"
          env: TOXENV=py35,py35-deps
        - python: "3.6"
          env: TOXENV=py36,py36-deps
        - python: "3.7"
          env: TOXENV=py37,py37-deps
        - python: "3.8"
          env: TOXENV=py38,py38-deps

install:
    - travis_retry pip install -U pip setuptools
    - travis_retry pip install -U tox coveralls coverage

script:
    - travis_retry tox

after_success:
    - coverage combine
    - coveralls

notifications:
    email: mh@gocept.com

cache:
  pip: true
  directories:
    - eggs/
